// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://lipdldnwrpcvmvoaqdfg.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6ImxpcGRsZG53cnBjdm12b2FxZGZnIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NDczMzkzMzcsImV4cCI6MjA2MjkxNTMzN30.UBbSi0BTJWsS1Xryehr74GnH_0FLVkItHpjahaRJpKk";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY);